### ISSUE TITLE
create "who trust us" section

### ISSUE THREAD

**Issue by lautaro450** [coderbunker/coderbunker.com#40] opened 2019-03-09 09:03 UTC
- [ ] Create a section inside the landing page with all the coderbunker clients logos ( i.e LVMH logo)
- [ ] Create a link to customers profiles with project details (like a learn more button)

reference: https://docs.google.com/document/d/19-4n9GltRmA69bYK7QEjpmAgROoQEQ5obVfvRHuOAcQ/

**Comment by echolabstech** [comment] 2019-04-13 11:05
duplicate of #48 and #49

**Closed by echolabstech** 2019-04-13 11:05 UTC
